server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/web?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.web.entity
logging:
  level:
    com:
      web:
        mapper : debug